name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Building stage
        run: swift build --configuration release

      - name: Testing stage
        run: swift test --configuration release

      - name: Generating executable binary stage
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: .build/release/SwiftWhisperProxy
